version: '3.8'
services:
  movies_db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'movies'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
